factor = 2 ** (1/12)

print("C: ",1*(factor)**0)
print("bD: ",1*(factor)**1)
print("D: ",1*(factor)**2)
print("bE: ",1*(factor)**3)
print("E: ",1*(factor)**4)
print("F: ",1*(factor)**5)
print("bG: ",1*(factor)**6)
print("G: ",1*(factor)**7)
print("bA: ",1*(factor)**8)
print("A: ",1*(factor)**9)
print("bB: ",1*(factor)**10)
print("B: ",1*(factor)**11)
print("C(high 8): ", 1*(factor)**12)
print("bD(high 8): ",1*(factor)**13)
print("D(high 8): ",1*(factor)**14)
print("bE(high 8): ",1*(factor)**15)
print("E(high 8): ",1*(factor)**16)
print("F(high 8): ",1*(factor)**17)
print("bG(high 8): ",1*(factor)**18)
print("G(high 8): ",1*(factor)**19)
print("bA(high 8): ",1*(factor)**20)
print("A(high 8): ",1*(factor)**21)
print("bB(high 8): ",1*(factor)**22)
print("B(high 8): ",1*(factor)**23)
print("C(high 16): ", 1*(factor)**24)

for i in range(1,20):
        print(i+1,'/',i,' = ', (i+1)/i )
